bk_platform:
    resource: "@BKPlatformBundle/Resources/config/routing.yml"    

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
index:
    pattern:  /
    defaults: { _controller: BKPlatformBundle:Security:login }
login:
    pattern:   /login
    defaults:  { _controller: BKPlatformBundle:Security:login }

login_check:
    pattern:   /login_check

logout:
    pattern:   /logout