<?php

namespace BK\PlatformBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AmiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AmiRepository extends EntityRepository
{
 /*   public function myFind1($formvalue)
        {
		    $query = $this->_em->createQuery('SELECT g FROM BKPlatformBundle:Gestion g WHERE g.pseudo LIKE :formvalue');
			$query->setParameter('formvalue','%'. $formvalue .'%');
  
			return $query->getResult();
		}*/
}
